### ISSUE TITLE
Number of players

### ISSUE THREAD

**Issue by tanyiroe** [tomooda/IDAIR#11]
Can we have a flexible number of players instead of fixing it at 6? Does the algorithm work well with other numbers?

**Comment by tomooda** [comment]
You can have any number of players less than or equal to 6. If you enter only one player name at the beginning, you will have only one citizen player.

**Comment by tanyiroe** [comment]
Can it go up to 8 or 10 players?

**Comment by tomooda** [comment]
To accept 10 citizen players, we'll need to re-design the settings between RPG and ABM because we need to change the total population in the ABM.
