### ISSUE TITLE
Use different probabilities for patients with ICU beds and regular beds

### ISSUE THREAD

**Issue by tanyiroe** [tomooda/IDAIR#14]
The extent to which the disease rates change should be different for the ICU beds and regular beds. @tomooda, can you please work with Manh on this? I have informed him and he can share with you more on how he did it in his previous version.

**Comment by tomooda** [comment]
solved by https://github.com/tomooda/IDAIR/commit/9f705c84cd9b32ffa0ca309b804514bac412f2b9
