### ISSUE TITLE
prevention compliance rate

### ISSUE THREAD

**Issue by tomooda** [tomooda/IDAIR#20]
Current status of prevention policy

Instead of the number given by policymakers, show the percentage of compliance by citizens

**Comment by tanyiroe** [comment]
![image](https://github.com/tomooda/IDAIR/assets/146925601/11e35e17-76eb-4407-9d21-b23661b7f95e)
To have a 'N.A.' button in addition to the yes/no button, as this is needed for the mask resource

**Comment by tomooda** [comment]
@tanyiroe Vaccination resource cards are given to only limited players by the gamemaster. I'll compute the compliance rate by only players who explicitly answered "yes" or "no".

**Comment by tanyiroe** [comment]
The default for all players should be no since they are all not vaccinated to start with. Only when a player takes the vaccination resource card, then it will change to yes and that will affect the vaccination rate.

**Comment by tomooda** [comment]
@tanyiroe So, the PM's vaccination card does not affect the compliance rate of vaccination?

**Comment by tanyiroe** [comment]
the PM's vaccination card only affects the number of vaccine resource given to the citizen table.

**Comment by tomooda** [comment]
@tanyiroe I understand. Thank you!

**Comment by tomooda** [comment]
solved by https://github.com/tomooda/IDAIR/commit/df9e1009ffc2f0e420dcaf42c008a5242606a925
