### ISSUE TITLE
Remove susceptibles curve from population chart

### ISSUE THREAD

**Issue by SergeStinckwich** [tomooda/IDAIR#5]
Remove susceptible curve from the population chart, as most of the time, there are too much susceptibles to see the other curves. Or maybe deselect the curve by default, when you launch a new game

<img width="825" alt="Screenshot 2023-10-04 at 14 03 39" src="https://github.com/tomooda/IDAIR/assets/327334/bf76034d-f834-4484-b89d-e5b1c95d8524">
<img width="834" alt="Screenshot 2023-10-04 at 14 03 51" src="https://github.com/tomooda/IDAIR/assets/327334/52098e96-14fe-4d5c-9164-883b2e0f2524">

**Comment by tomooda** [comment]
solved by https://github.com/tomooda/IDAIR/commit/12b4fe2c50941b78094d63b04aebcffcdba4100e
