### ISSUE TITLE
Medical status tab shows cumulated number of cases or current number of cases ?

### ISSUE THREAD

**Issue by SergeStinckwich** [tomooda/IDAIR#7]
When you look at the population chart tab and the medical status tab, this is difficult to understand the difference of numbers for recovered. I guess that for the medical status bar, this is cumulated number of recovered?

<img width="959" alt="Screenshot 2023-10-04 at 14 08 12" src="https://github.com/tomooda/IDAIR/assets/327334/cb8adf1f-60bb-4df7-ad65-10a3ee3b6caa">

Maybe we should say cumulated numbers and not current number of cases?

<img width="962" alt="Screenshot 2023-10-04 at 14 08 21" src="https://github.com/tomooda/IDAIR/assets/327334/9926d56b-062a-4e1c-82c9-86c8449cb56a">

**Comment by tomooda** [comment]
The number of recovered in the population chart and the medical status chart are both the current number of citizens in the recovered state.
