### ISSUE TITLE
How to reflect policies restrictions to players?

### ISSUE THREAD

**Issue by SergeStinckwich** [tomooda/IDAIR#9]
We need a way to reflect some restrictions due to policies in the UI, so that the citizen are informed.
For example, if citizen want to go a bar and there is a quarantine put in place by policy makers, we need to reflect that to the citizen (either in the RPG or in the UI of the ABM).

**Comment by kuriajoel** [comment]
Also on the same, it would be great to represent policy reinforcements (actual consequences of not complying with a policy such as fines, etc)

**Comment by tomooda** [comment]
It's an interesting topic, but I think it's up to the game rule of the RPG rather than ABM.

**Comment by tanyiroe** [comment]
Yes I agree with Tomo, this is more for the RPG game play. We do have a part where we ask the policymakers to convey to the citizens what policies they have implemented. This happens during the intervals between every round.
